In [1]:
import numpy as np

In [2]:
list_1 = [1,2,3,4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
arr1 = np.array(list_1)

In [5]:
arr1

array([1, 2, 3, 4])

In [6]:
arr1.itemsize

4

In [7]:
list1 = list_1
list2 = list1

In [8]:
list2


[1, 2, 3, 4]

In [9]:
arr2 = np.array([list1, list2])

In [10]:
arr2.shape

(2, 4)

### 合并操作

In [11]:
x = np.array([1,2,3,4])
y = np.array([4,5,6,7])
print(x,y)

[1 2 3 4] [4 5 6 7]


In [12]:
 np.concatenate([x,y])

array([1, 2, 3, 4, 4, 5, 6, 7])

In [13]:
z = np.array([7,8,9,10])
s = np.concatenate([x,y,z])
s

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [14]:
s = s.reshape((3,4))
t = s
t

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [15]:
np.concatenate([s,t])

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [16]:
np.concatenate([s,t], axis=1) # 等于np.hstack()

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 7,  8,  9, 10,  7,  8,  9, 10]])

In [17]:
np.concatenate([s,t], axis=0) # 等于np.vstack()

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

### 分割操作

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.split(x, [3,7])

[array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]

In [20]:
np.split(x, [5])

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [21]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.split(y,[2],axis=1)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [23]:
x = x.reshape(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
np.split(x,2,axis=0)

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]

In [25]:
a,b,c = np.split(x,[3,4],axis=1)
a,b,c

(array([[0, 1, 2],
        [5, 6, 7]]), array([[3],
        [8]]), array([[4],
        [9]]))

In [26]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
yl, yr = np.split(y,[-1],axis=1)
yr

array([[ 3],
       [ 7],
       [11],
       [15]])

In [28]:
yr[:, 0]

array([ 3,  7, 11, 15])

>`总结以上测试,发现参数列表如果只有一个元素代表按照维度等比例分割矩阵
多个元素,就需要以列表的形式传参,代表按照参数即索引进行分割`

参照前面不同维度写法,不写参数维度,也有类似的方法`行方向np.vsplit()`和的`水平方向np.hsplit()`

### np.array 中的运算

- 数组和常数的运算

In [29]:
a = np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [30]:
a+1

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17]])

In [31]:
a-1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
a*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [33]:
a/2

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5,  8. ]])

In [34]:
a//2 #整除运算

array([[0, 1, 1, 2],
       [2, 3, 3, 4],
       [4, 5, 5, 6],
       [6, 7, 7, 8]], dtype=int32)

In [35]:
1/a

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.2       ,  0.16666667,  0.14285714,  0.125     ],
       [ 0.11111111,  0.1       ,  0.09090909,  0.08333333],
       [ 0.07692308,  0.07142857,  0.06666667,  0.0625    ]])

- 数组和数组之间的运算是对应元素之间的运算

In [36]:
a = np.arange(4).reshape(2,2)
b = np.full((2,2), 10, dtype='int32')
a,b

(array([[0, 1],
        [2, 3]]), array([[10, 10],
        [10, 10]]))

In [37]:
a+b

array([[10, 11],
       [12, 13]])

In [38]:
a-b

array([[-10,  -9],
       [ -8,  -7]])

In [39]:
a/b

array([[ 0. ,  0.1],
       [ 0.2,  0.3]])

In [40]:
a*b

array([[ 0, 10],
       [20, 30]])

In [47]:
#看上面的乘法,显然是对应元素的相乘,并不是矩阵的乘法
#想要矩阵的乘法,需要用到 dot()函数
a,b

(array([[0, 1],
        [2, 3]]), array([[10, 10],
        [10, 10]]))

In [48]:
a.dot(b)#矩阵乘法

array([[10, 10],
       [50, 50]])

- 矩阵和向量的运算

In [51]:
v = np.array([1,2])
v

array([1, 2])

In [50]:
a

array([[0, 1],
       [2, 3]])

In [52]:
v+a

array([[1, 3],
       [3, 5]])